constants = {
	"DATA_SECTION_START_BYTE":		58,
	"IDLE_BATCHES_PER_PACKET":		7,
	"ATTITUDE_BATCHES_PER_PACKET": 5,
	"FLASHBURST_BATCHES_PER_PACKET": 7,
	"FLASHCMP_BATCHES_PER_PACKET": 6,
	"LOWPOWER_BATCHES_PER_PACKET": 5,

	"ERROR_TIME_BUCKET_SIZE": 300,

	"Ms_and_Bs": {
		"A_TEMP_M":					32,
		"A_TEMP_B":					0,
		"A_LED_SNS_M":				650,
		"A_LED_SNS_B":				0,
		"A_LF_SNS_M":				45,
		"A_LF_SNS_B":				-960,
		"A_LF_OSNS_M":				72,
		"A_LF_OSNS_B":				0,
		"A_LF_VOLT_M":				14,
		"A_LF_VOLT_B":				0,
		"A_L_SNS_M":					20,
		"A_L_SNS_B":					150,
		"A_L_VOLT_M":				14,
		"A_L_VOLT_B":				0,
		"A_LREF_M":					14,
		"A_LREF_B":					0,
		"A_PANELREF_M":				6,
		"A_PANELREF_B":				0,
		"A_IR_AMB_M":				7,
		"A_IR_AMB_B":				-11657,
		"A_GYRO_M":					1,
		"A_GYRO_B":					32750,
		"A_ACCEL_M":					1,
		"A_ACCEL_B":					32768,
		"A_MAG_M":					11,
		"A_MAG_B":					2800,
		"A_RAD_TEMP_M":				16,
		"A_RAD_TEMP_B":				2000,
		"A_IMU_TEMP_M":				1,
		"A_IMU_TEMP_B":				20374
	}
}
